// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD8oNnS3ANPOAOovSJh3zlRkcP040nDMg',
    appId: '1:260518214604:web:577443b5c2fbeec44a7b69',
    messagingSenderId: '260518214604',
    projectId: 'socializz-2772',
    authDomain: 'socializz-2772.firebaseapp.com',
    storageBucket: 'socializz-2772.appspot.com',
    measurementId: 'G-TJZF3ZE8PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QxMPuJKBc2eG5btbAYXar7QhDGXi-RU',
    appId: '1:260518214604:android:a6793ba460ceadce4a7b69',
    messagingSenderId: '260518214604',
    projectId: 'socializz-2772',
    storageBucket: 'socializz-2772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqdB3X16Puy-KlLARYBcRIEXj5mzhMDvU',
    appId: '1:260518214604:ios:48f47dca1425cd1b4a7b69',
    messagingSenderId: '260518214604',
    projectId: 'socializz-2772',
    storageBucket: 'socializz-2772.appspot.com',
    iosClientId: '260518214604-l8s0k7qn9t1qacpe3tptlg46ihs043nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socializz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqdB3X16Puy-KlLARYBcRIEXj5mzhMDvU',
    appId: '1:260518214604:ios:b6fb686c4846d6094a7b69',
    messagingSenderId: '260518214604',
    projectId: 'socializz-2772',
    storageBucket: 'socializz-2772.appspot.com',
    iosClientId: '260518214604-kkhmd7k74a3egiakg2768og1tjpi5lmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.socializz.RunnerTests',
  );
}
